name: Java CI (Windows)

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # https://github.com/actions/checkout/issues/135#issuecomment-602171132
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode test
